use std::fmt::Write;
use std::fs;
use std::path::PathBuf;
use wgsl_to_wgpu::{MatrixVectorTypes, WriteOptions, create_shader_module};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Путь к папке с вашими шейдерами
    let shaders_dir = PathBuf::from("src/shaders");

    // Говорим Cargo пересобирать проект, если что-то изменилось внутри этой папки
    println!("cargo:rerun-if-changed=src/shaders");

    // Читаем все файлы в папке src/shaders
    for entry in fs::read_dir(shaders_dir)? {
        let entry = entry?;
        let path = entry.path();

        // Проверяем, что это файл с расширением .wgsl
        if path.is_file() && path.extension().and_then(|s| s.to_str()) == Some("wgsl") {
            let file_name = path.file_stem().unwrap().to_str().unwrap();
            let wgsl_source = fs::read_to_string(&path)?;

            let mut text = String::new();
            writeln!(&mut text, "// File automatically generated by build.rs. DO NOT EDIT.")?;

            // Генерируем код с настройками для encase и glam
            text += &create_shader_module(
                &wgsl_source,
                &format!("{file_name}.wgsl"),
                WriteOptions {
                    derive_bytemuck_vertex: false,
                    derive_encase_host_shareable: true,
                    matrix_vector_types: MatrixVectorTypes::Glam,
                    rustfmt: true,
                    validate: Some(Default::default()),
                    ..Default::default()
                },
            )
            .inspect_err(|error| error.emit_to_stderr_with_path(&wgsl_source, &path.to_str().unwrap()))
            .map_err(|_| format!("Failed to validate shader: {file_name}"))?;

            // Сохраняем рядом с оригиналом, без всяких суффиксов (например: src/shaders/cube.rs)
            let out_path = path.with_extension("rs");
            fs::write(out_path, text.as_bytes())?;
        }
    }

    Ok(())
}
