[package]
name = "mrrt"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
winit = { version = "0.30", features = ["android-native-activity"] }
env_logger = "0.11"
log = "0.4"
wgpu = "30.0"
pollster = "1.0"
glam = { version = "0.33", features = ["encase", "bytemuck"] }
encase = "0.12"
bytemuck = { version = "1.16", features = ["derive"] }
rayon = "1.12"

[build-dependencies]
wgsl_to_wgpu = "0.19"
